# Generated by Django 5.1.7 on 2025-03-20 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('E_image', models.ImageField(upload_to='E_image')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
