# Generated by Django 5.1.7 on 2025-03-20 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S_image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('E_image', models.ImageField(upload_to='E_image')),
                ('E_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='all',
        ),
    ]
